### ISSUE TITLE
Remember last used weight

### ISSUE THREAD

**Issue by maxwellhibbert** [phosphor-icons/sketch#14]
It'd be very handy if the icon selection view would remember the last used icon weight, or if that's not possible to have the ability to set a default. When working on a project that only uses a weight that's not the default, it gets quite tedious switching via the dropdown each time.

**Comment by rektdeckard** [comment]
The site supports URL query parameters. You can just bookmark https://phosphoricons.com/?weight="duotone" or whatever your weight is. It's always reflected in the URL bar whenever you make a change.

**Comment by rektdeckard** [comment]
We now remember the last icon weight you used, and this should persist between sessions, as well as survive app quits and updates.

**Comment by maxwellhibbert** [comment]
> We now remember the last icon weight you used, and this should persist between sessions, as well as survive app quits and updates.

Sorry for the very late reply @rektdeckard
I've just tested this updated version and the weight is still not remembered.

https://github.com/user-attachments/assets/647ceee8-c200-4336-b3b9-11cea362f2ed
