### ISSUE TITLE
Phosphor Sketch plugin won’t update

### ISSUE THREAD

**Issue by CrisSketch** [phosphor-icons/sketch#15]
**Describe the bug**

Hello awesome Phosphor folks!

A user reached out to report that they were having trouble updating your Plugin.

We checked the report and could replicate the issue. From dealing with this in the past we believe to be something related to the XML generated that cannot find the correct URL to download. But we are  not sure. Would you mind checking this on your end? 🙏

**Steps to Reproduce**

1. Install an older version of the plugin using the Sketch version 100
2. Open a Sketch document (a new document works fine) 
4. Go to Plugins > Manage Plugins 
5. Click "Update"
6. Observe that nothing happens 

**Expected behavior**

When clicking "Update" the plugin should update. 

**Screenshots**

https://github.com/phosphor-icons/sketch/assets/123388460/ea1f098d-21e1-4596-ab15-f5be85f6d11f

**Context (please complete the following information):**

- OS: macOS 14.5
- Browser/Environment Sketch v.100
- Version 2.1.3

**Additional notes**

**Comment by vvdheuvel** [comment]
https://github.com/phosphor-icons/sketch/releases/tag/v2.1.3
Manifest file (Contents/Sketch/manifest.json) still states:"version": "2.1.0"

**Comment by rektdeckard** [comment]
@CrisSketch thanks for the report, and @vvdheuvel thanks for spotting the issue! Fix incoming.

**Comment by maxwellhibbert** [comment]
still doesn't update and release page still has v2.1.0

**Comment by rektdeckard** [comment]
Fixed and should be updating as usual now! https://github.com/phosphor-icons/sketch/releases/tag/v2.1.4
